version: "3"

services:
  pihole-unbound:
    build: .
    container_name: pihole-unbound
    image: pihole-unbound:latest
    ports:
      - "${PIHOLE_ServerIP}:53:53/tcp"
      - "${PIHOLE_ServerIP}:53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
    environment:
      ServerIp: $PIHOLE_ServerIP
      TZ: $PIHOLE_TIMEZONE
      WEBPASSWORD: $PIHOLE_PASSWORD
      PIHOLE_DNS_: 127.0.0.1#5335;127.0.0.1#5335
      DNSSEC: "true"
    volumes:
      - ~/.pihole-unbound/etc-pihole/:/etc/pihole:rw
      - ~/.pihole-unbound/etc-dnsmasq.d/:/etc/dnsmasq.d:rw
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
